### ISSUE TITLE
DM: ArrayIndexOutOfBoundsException

### ISSUE THREAD

**Issue by kofman-alex** [speedd-project/speedd#28]
In the TrafficDecisionMakerBolt.get_criticalDensity(location), if location is null or wrong, the get_cellId() returns -1, and the index addressed is '-2' - out of bounds.
Should harden this code.

The stack trace is below.
java.lang.RuntimeException: java.lang.ArrayIndexOutOfBoundsException: -2
        at backtype.storm.utils.DisruptorQueue.consumeBatchToCursor(DisruptorQue
ue.java:128) ~[storm-core-0.9.3.jar:0.9.3]
        at backtype.storm.utils.DisruptorQueue.consumeBatchWhenAvailable(Disrupt
orQueue.java:99) ~[storm-core-0.9.3.jar:0.9.3]
        at backtype.storm.disruptor$consume_batch_when_available.invoke(disrupto
r.clj:80) ~[storm-core-0.9.3.jar:0.9.3]
        at backtype.storm.daemon.executor$fn__3441$fn__3453$fn__3500.invoke(exec
utor.clj:748) ~[storm-core-0.9.3.jar:0.9.3]
        at backtype.storm.util$async_loop$fn__464.invoke(util.clj:463) ~[storm-c
ore-0.9.3.jar:0.9.3]
        at clojure.lang.AFn.run(AFn.java:24) [clojure-1.5.1.jar:na]
        at java.lang.Thread.run(Thread.java:745) [na:1.7.0_79]
Caused by: java.lang.ArrayIndexOutOfBoundsException: -2
        at org.speedd.dm.TrafficDecisionMakerBolt.get_criticalDensity(TrafficDec
isionMakerBolt.java:198) ~[stormjar.jar:na]
        at org.speedd.dm.TrafficDecisionMakerBolt.computeNewRate(TrafficDecision
MakerBolt.java:153) ~[stormjar.jar:na]

**Comment by echozheng** [comment]
yes, i also get this problem.
i modify the funciton - "get_cellId" in the class TrafficDecisionMakerBolt.
just set the sensors by order, not the "-1".
cellId.put("0024a4dc00003356", 1);
cellId.put("0024a4dc00003354", 2);
cellId.put("0024a4dc0000343c", 3);
cellId.put("0024a4dc0000343b", 4);
cellId.put("0024a4dc00003445", 5);
cellId.put("0024a4dc00001b67", 6);
cellId.put("0024a4dc00003357", 7);
cellId.put("0024a4dc00000ddd", 8);
cellId.put("0024a4dc00003355", 9);
cellId.put("0024a4dc000021d1", 10);
cellId.put("0024a4dc0000343f", 11);
cellId.put("0024a4dc00001b5c", 12);
cellId.put("0024a4dc000025eb", 13);
cellId.put("0024a4dc000025ea", 14);
cellId.put("0024a4dc00001c99", 15);
cellId.put("0024a4dc000013c6", 16);
cellId.put("0024a4dc00003444", 17);
cellId.put("0024a4dc000025ec", 18);
cellId.put("0024a4dc0000343e", 19);
