### ISSUE TITLE
TTransportException: java.net.ConnectException: Connection refused (Connection refused)

### ISSUE THREAD

**Issue by bryanleekw** [speedd-project/speedd#68]
I followed the following steps 
Stream events into SPEEDD (example for the traffic management use case):
1. Open ssh to the client container
2. cd /opt/src/speedd/speedd-runtime/scripts/traffic
3. ./playevents-traffic-docker

However, it shows ERROR on kafka I/O, may I know anyone know why?
root@db5e62928fe5:/opt/speedd/speedd/speedd-runtime/scripts/traffic# ./playevents-traffic-docker
Loading producer configuration from ../producer-docker.properties
Event file: simulator_data_incident_shortened.csv
Sending events to topic: speedd-traffic-in-events
Properties loaded:{bootstrap.servers=kafka:9092, compression.codec=none, value.serializer=org.apache.kafka.common.serialization.StringSerializer, producer.type=sync, key.serializer=org.apache.kafka.common.serialization.StringSerializer}
15 [main] INFO org.speedd.TimedEventFileReader - Open file simulator_data_incident_shortened.csv for read.
29 [main] INFO org.apache.kafka.clients.producer.ProducerConfig - ProducerConfig values: 
	value.serializer = class org.apache.kafka.common.serialization.StringSerializer
	key.serializer = class org.apache.kafka.common.serialization.StringSerializer
	block.on.buffer.full = true
	retry.backoff.ms = 100
	buffer.memory = 33554432
	batch.size = 16384
	metrics.sample.window.ms = 30000
	metadata.max.age.ms = 300000
	receive.buffer.bytes = 32768
	timeout.ms = 30000
	max.in.flight.requests.per.connection = 5
	bootstrap.servers = [kafka:9092]
	metric.reporters = []
	client.id = 
	compression.type = none
	retries = 0
	max.request.size = 1048576
	send.buffer.bytes = 131072
	acks = 1
	reconnect.backoff.ms = 10
	linger.ms = 0
	metrics.num.samples = 2
	metadata.fetch.timeout.ms = 60000

155 [main] WARN org.apache.kafka.clients.producer.ProducerConfig - The configuration compression.codec = null was supplied but isn't a known config.
155 [main] WARN org.apache.kafka.clients.producer.ProducerConfig - The configuration producer.type = null was supplied but isn't a known config.
155 [main] INFO org.speedd.TimedEventFileReader - Open producer to send to kafka: {bootstrap.servers=kafka:9092, compression.codec=none, value.serializer=org.apache.kafka.common.serialization.StringSerializer, producer.type=sync, key.serializer=org.apache.kafka.common.serialization.StringSerializer}
156 [main] INFO org.speedd.TimedEventFileReader - Start streaming events, start timestamp: 1513567782570
258 [kafka-producer-network-thread | producer-1] WARN org.apache.kafka.common.network.Selector - Error in I/O with kafka/172.17.0.4
java.net.ConnectException: Connection refused
	at sun.nio.ch.SocketChannelImpl.checkConnect(Native Method)
	at sun.nio.ch.SocketChannelImpl.finishConnect(SocketChannelImpl.java:744)
	at org.apache.kafka.common.network.Selector.poll(Selector.java:238)
	at org.apache.kafka.clients.NetworkClient.poll(NetworkClient.java:192)
	at org.apache.kafka.clients.producer.internals.Sender.run(Sender.java:191)
	at org.apache.kafka.clients.producer.internals.Sender.run(Sender.java:122)
	at java.lang.Thread.run(Thread.java:748)

**Comment by bryanleekw** [comment]
Running the following storm command to submit topology to storm, but got connection refused error, so may I seek your kind help on how can I solve this issue?

$STORM_CMD jar $SPEEDD_RUNTIME_LIB/speedd-runtime-0.0.1-SNAPSHOT-jar-with-dependencies.jar org.speedd.SpeeddRunner \
-D nimbus.host=nimbus -D nimbus.thrift.port=6627 \
-m remote \
-Dproducer.type=sync -Dcompression.codec=none -Dserializer.class=org.speedd.kafka.JsonEventEncoder \
-Dmetadata.broker.list=kafka:9092 \
-Dzookeeper.connect=zk:2181 \
-Dzookeeper.connection.timeout.ms=1000000 \
-Dtopic.in.events=speedd-traffic-in-events \
-Dtopic.out.events=speedd-traffic-out-events \
-Dtopic.actions=speedd-traffic-actions \
-Dtopic.actions.confirmed=speedd-traffic-actions-confirmed \
-Dtopic.admin=speedd-traffic-admin \
-Dproton.epnPath=CNRSIntegration.json \
-Dspeedd.inEventScheme=org.speedd.traffic.TrafficAimsunReadingScheme \
-Dspeedd.enricherPath=rochade_sensor_and_aimsun_labels_partitions.csv \
-Dspeedd.topology.class=org.speedd.traffic.TrafficManagementTopology \
-Dspeedd.cepParallelismHint=1 \
-Dtopology.debug=false \
&
